### ISSUE TITLE
Styled components recommendations

### ISSUE THREAD

**Issue by konrad147** [reakit/reakit#203]
Hi,

I wanted to ask about `styled-components` recommendations. As I see that the most (or all) of the components are wrapped into `styled` function. As I understand `styled-components` recommendation is to avoid that and use wrappers to apply a styling.
From `styled-components` documentation:

> Consider carefully whether to wrap your own components in a styled component, when it isn't necessary. You will disable the automatic whitelisting of props, and reverse the recommended order of styled components and structural components.

Why did you choose to use that approach?

**Comment by diegohaz** [comment]
Hi, @konrad147. Thanks for asking.

That recommendation works well for apps, but that's not entirely true for libraries.

In our website app, you can see that we're following it:
https://github.com/reakit/reakit/blob/c755118e9caaf3d899f630ea314bd899b2d4f85f/packages/website/src/components/Footer.js#L28-L85


But in the library we need control over the underlying element, which would not be possible if we just rendered the styled component. For example, this is how we render the element in the end:
https://github.com/reakit/reakit/blob/c755118e9caaf3d899f630ea314bd899b2d4f85f/packages/reakit/src/as.tsx#L55-L71

That `T` is needed in order to make the `as` prop work.
