### ISSUE TITLE
What most interests you about this library?

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#261]
I want to improve the way we describe the lib in our website and README. 

Currently, it highlights **interactivity** as the most important thing, and **composability**, **accessibility** and **reliability** as secondary features. But that's pretty much my point of view, things I value of my projects and focused when I was first building this library. 

But I'm sure that others will see different things. For example, I've heard people saying **unopionionated**, **decoupled**, **flexible**, **scalable** etc.

It would be really helpful if you guys could share your thoughts about it.

**What most interests you about this library?**

**Comment by jxom** [comment]
Accessibility for sure! I feel that accessibility can be easily neglected when building a UI, and having a library like Reakit to help us with accessibility concerns is amazing - and I believe the reliability and composability features follow through and help us build accessible interfaces easier as well!

**Comment by vinay72** [comment]
I think ease of Use is a Feature on which one should focus on . UI And UX has a great impact so you also keep that in Mind also.

**Comment by codyaverett** [comment]
^^UI/UX all the way.

**I can tell that a lot of thought goes into this project.**

**I've been thinking about what to say here for a week.**  
**Here are some opinionated words** **(I think I'm right! haha)**

* Reakit simplifies a large majority of my current work projects. :finnadie: :blue_heart:
* I love how Reakit uses [Constate](https://github.com/diegohaz/constate) `I actually found Reakit through using constate.`  Thx [@Swizec](https://twitter.com/Swizec).
* Styled-Components. :nail_care: :blue_heart:
* I'm glad it supports accessibility cases. `b/c idk much of anything about supporting accessibility yet.` :see_no_evil: :hear_no_evil: :speak_no_evil:
* It's quick and easy to search through documentation by pressing the `/` key while [on the website](https://reakit.io/components/box).
* Superb Typescript support.
* Nice and welcoming atmosphere. :earth_americas:
* Great documentation for humans.
* Feels very active. :running:
* Robust. :muscle:
* Good website, logo, and **"dark mode"** theme (By far, one of my favorite features :neckbeard:)
* Compound components/containers `e.g. <Sidebar.Container>... , <Sidebar>... `
* Everything in here is like... super-composable.
* Reakit is a great topic for water cooler conversations at the office. :potable_water:

> Reakit is a versatile toolbox filled with simple patterns that helps my components feel like they won't blow up in production. - Cody Averett

> Reakit helps my team of 4 engineers look productive and do great things. - Cody Averett

I love that [Reakit accepts donations](https://opencollective.com/reakit). :love_letter:
> P.S. I so badly want a bunch of reakit dev stickers I can pass around at work. @diegohaz how can we make that happen? Also, I would like to have a fitted **"dark mode"** t-shirt.  And a flag! haha. :) No pressure, but lemme know.

The only negativity I could even throw out there is that Reakit could still be better! :scream_cat: :1st_place_medal: Also, I am not telepathic, but I am confident Reakit will be better in the future.

Great work @diegohaz @Thomazella and @PlayMa256 . You've all been a great help to me personally.
Also, thanks to all contributors because you're awesome too.

Fin.

**Comment by onluiz** [comment]
It is easy to customize and avoids the need of creating a new library or to modify current project structure to adapt.

It is perfect to apply design systems too.

**Comment by diegohaz** [comment]
Thank you guys. These feedbacks helped us choose better the direction of the library for v1.
