### ISSUE TITLE
RFC: Hooks

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#288]
UPDATE: Some gists with ideas:

- https://gist.github.com/diegohaz/f0b3b198745e381c37c60f317212d546
- https://gist.github.com/mattfwood/79c8fb52abfeeb71b6de32c53cdf1bca

----

[React hooks](https://reactjs.org/docs/hooks-intro.html) were announced and will be available in React 16.7. I'm opening this issue to talk about a future addition (or maybe an eventual replacement) on Reakit's API.

My initial idea is to expose hooks instead of components and let the user choose the underlying element in a more straightforward way. The hooks will return objects with html attributes that can be passed direct to elements.

Today:
```jsx
import { Popover } from "reakit";

const MyPopover = () => (
  <Popover.Container initialState={{ visible: true }}>
    {popover => (
      <Popover.Toggle {...popover}>
        Toggle
        <Popover placement="top" {...popover}>
          <Popover.Arrow />
          Popover
        </Popover>
      </Popover.Toggle>
    )}
  </Popover.Container>
);
```

Tomorrow:
```jsx
import { usePopover } from "reakit";

function MyPopover() {
  const { toggle, popover, arrow } = usePopover({ placement: "top", visible: true });
  return (
    <button {...toggle}>
      Toggle
      <div {...popover}>
        <div {...arrow} />
        Popover
      </div>
    </button>
  );
}
```

The returned object would look like this:
```jsx
{
  toggle: {
    className: "HiddenToggle-kd7ngs-0",
    onClick: () => toggle(),
    "aria-expanded": false,
    "aria-haspopup": true
  },
  popover: {
    className: "Popover-s6tfv8-0",
    "aria-hidden": true,
    "data-placement": "bottom",
    "role": "group"
  },
  arrow: {
    className: "PopoverArrow-sc-1tkjw1-0",
    children: (
      <svg viewbox="0 0 30 30">
        <path class="stroke"
              d="M23.7,27.1L17,19.9C16.5,19.3,15.8,19,15,19s-1.6,0.3-2.1,0.9l-6.6,7.2C5.3,28.1,3.4,29,2,29h26 C26.7,29,24.6,28.1,23.7,27.1z"
        >
        </path>
        <path class="fill"
              d="M23,27.8c1.1,1.2,3.4,2.2,5,2.2h2H0h2c1.7,0,3.9-1,5-2.2l6.6-7.2c0.7-0.8,2-0.8,2.7,0L23,27.8L23,27.8z"
        >
        </path>
      </svg>
    )
  }
}
```

The hooks would be decoupled so the users could use their own state handlers with it (just as they can do today by replacing `Popover.Container` for something else):

```jsx
import { useState } from "react";
import { usePopover, usePopoverState } from "reakit";

function MyPopover() {
  // const state = usePopoverState({ visible: true });

  const [visible, setVisible] = useState(true);
  const state = {
    visible,
    toggle: () => setVisible(!visible),
    show: () => setVisible(true),
    hide: () => setVisible(false)
  };

  const { toggle, popover, arrow } = usePopover({ placement: "top", ...state });

  return (
    <button {...toggle}>
      Toggle
      <div {...popover}>
        <div {...arrow} />
        Popover
      </div>
    </button>
  );
}
```

Composing multiple hooks could be as simple as spreading two objects on elements:
```jsx
<div {...overlay} {...portal} />
```

But, since they can have conflicting attributes (like both having `ref`, `onClick` etc.), we could expose a `compose` helper that would guarantee that those attributes would be composed, not overwritten.

Today:
```jsx
import { Overlay, Portal } from "reakit";

const Modal = () => (
  <Overlay.Container>
    {overlay => (
      <Overlay as={Portal} {...overlay}>Overlay</Overlay>
    )}
  </Overlay.Container>
);
```

Tomorrow:
```jsx
import { useOverlay, usePortal, compose } from "reakit";

function Modal() {
  const { portal } = usePortal();
  const { overlay } = useOverlay();
  return <div {...compose(portal, overlay)}>Overlay</div>;
}
```

Well, these are just my initial thoughts, and actually I'm not sure if they make sense, so feedback is really appreciated.

cc @reakit/collaborators

**Comment by Thomazella** [comment]
This looks amazing? I'd say the only thing to watch out for is that people using the lib may not want to upgrade to hooks, or how to handle that transition for users. For my use case though, this looks positively great!

**Comment by mattfwood** [comment]
I think it's definitely possible to follow the same approach as Hooks themselves and offer exports like `useOverlay` as an additional option rather than a replacement. But it would need to be carefully implemented to avoid repetition.

I would be very interested in collaborating on this, @diegohaz. These examples make sense at a glance. I'd be up for going through all the higher order components and seeing how we can rethink them with hooks.

**Comment by diegohaz** [comment]
If we are going to export both hooks and components, I think we should definitely create components using hooks underneath.

> I'd be up for going through all the higher order components and seeing how we can rethink them with hooks.

That would be really useful! Before implementing it, we should make sure we have a consistent API that  not only covers the current use cases, but can possibly be extended to possibilities that we don't cover today.

One example is using `Popover` with `Portal`, which isn't possible today because we don't use refs. With hooks, it could look like this:
```jsx
import { usePopover, usePortal, compose } from "reakit";

function MyPopover() {
  const { popover, reference } = usePopover();
  const { portal } = usePortal();
  return (
    <div>
      <button {...reference} />
      <div {...compose(popover, portal)} />
    </div>
  );
}
```
`reference` would have a `ref` prop which `popover` would be aware of, so it could be easily positioned relative to it without relying on DOM structure (portal will detach it from its original node).

Also, there's a lot of questions to answer:
- Will hooks be stateful? That is, will `usePopover()` implement `usePopoverState()` automatically? Will there be the option to pass an alternative `usePopoverState()` like in my 4th snippet in the original post?
- What return from hooks? Will `usePopover()` return an object with all the elements and state, like `{ popover, reference, arrow, visible, toggle, show, hide }`?
- If `toggle` is the state action, how to name the toggle element (the one with `{ onClick: () => toggle() }`)? Maybe `toggleButton`?
- etc.

Any examples, questions, ideas are welcome. :)

**Comment by mattfwood** [comment]
@diegohaz I made a quick gist with an overview of all the components that use render props and would be good candidates for hooks:

https://gist.github.com/mattfwood/79c8fb52abfeeb71b6de32c53cdf1bca

The proposed "new" examples aren't meant to be a final suggestion in any way, it's just a generic example. 

Also I agree that if the intent is to export both, it would be preferred to create the components using hooks so that it'd be easier to export the custom hook itself as well as the component and avoid any duplicate code.

I think the questions you propose are important to consider. Unfortunately it's tough to say what the preferred dev experience for hooks will be in these early stages. I think we should consider using Dan Abramov's [`useFormInput` custom hook](https://youtu.be/dpw9EHDh2bM?t=3042) example as a template for now, since the React internal team has the most experience with hooks so far:

```jsx
function useFormInput(initialValue) {
  const [value, setValue] = useState(intialValue);
  function handleChange(e) {
    setValue(e.target.value);
  }

  return {
    value,
    onChange: handleChange,
  }
}

function Form() {
  const name = useFormInput('Mary');

  return (
    <input {...name />
  )
}
```

**Comment by diegohaz** [comment]
@mattfwood That `useFormInput` example is pretty much what I'm aiming for. 

I like that you only converted containers into hooks in your gist. That's something we should definitely do even if hooks don't work for other things.

But I wanted to go further and see if it's possible to replace all components by hooks. I put some examples that I had on my mind here: https://gist.github.com/diegohaz/f0b3b198745e381c37c60f317212d546

If we could make everything work with hooks and don't rely on DOM, Reakit could've been used within other React renderers (like react-native).

**Comment by Andarist** [comment]
Just my 2 cents - I was experimenting with hooks a little bit, looking also through many implementations in the wild and I came to conclusion that for ref-related hooks it's best to force people giving a ref to a library. It just seems like it composes best. Example:
```js
function Example() {
  const ref = useRef()
  useOnClickOutside(ref)
  useResizeObserver(ref)
  useSmoothScroller(ref)
  return <div  ref={ref}/>
}
```

**Comment by diegohaz** [comment]
@Andarist the alternative API would be this, right?
```jsx
function Example() {
  const ref1 = useOnClickOutside()
  const ref2 = useResizeObserver()
  const ref3 = useSmoothScroller()
  return <div ref={???} />
}
```

Are you aware of any downside besides having to compose the refs somehow? I guess that, since more refs are being created, this could affect performance, but I would be really surprised if the impact were significant.

**Comment by Andarist** [comment]
No - I'm not aware of any perf-related downsides to your solution (other than the hooks list gets longer with each ref per component, but it's probably insignificant). 

I just think that my proposed way of doing things composes better, because... you dont have to compose in any special way 😅 Just pass an argument and you are ready to go. It also allows passing a ref received from prop directly to the hook, so it just makes more sense to me (also when discussing this on twitter people seemed to lean towards my solution). I agree this looks quite different - because without hooks I probably wouldn't propose a similar solution, but with hooks it somehow changes my mind about this and after thinking about it a little bit it just seems like a better solution, even if you have to do a little bit of plumbing in your render function.

**Comment by diegohaz** [comment]
Just an update:

I've been experimenting around some APIs (applying them to my private projects). For now, I can say that It's not possible to have everything as hooks. We need components. But we can expose both. People building component libraries could take advantage of `usePopover`, while people using Reakit directly on their apps could use `<Popover />`.

`<Popover />` would implement `usePopover` underneath, so the code would be very minimal, no duplication.

Currently, I'm working on an accessible `<Form />` (and `useForm`) for a private project. It'll likely addresses #161.

**Comment by jxom** [comment]
That would be fantastic @diegohaz!

**Comment by diegohaz** [comment]
Closing in favor of #345
