### ISSUE TITLE
V1 API 

### ISSUE THREAD

**Issue by lluia** [reakit/reakit#352]
**V1** looks cool, congrats @diegohaz! 🎊 💪🏻

Looking at the docs, I'm wondering if it doesn't end too verbose 🤔

I believe now you need to import the component and its corresponding hook to get it to work?

```jsx
import { useTabState, Tab, TabList, TabPanel } from "reakit";

function Tabs() {
  const tab = useTabState({ selectedId: "orders" });
  return (
    <Fragment>
      <TabList {...tab}>
        <Tab {...tab} stopId="orders">Orders</Tab>
        <Tab {...tab} stopId="transactions">Transactions</Tab>
      </TabList>
      <TabPanel {...tab} stopId="orders">
        <p>List of orders</p>
      </TabPanel>
      <TabPanel {...tab} stopId="transactions">
        <p>List of transactions</p>
      </TabPanel>
    </Fragment>
  );
}
``` 
Rather than just doing one or the other?
```jsx
import { Tab, TabList, TabPanel, useTabState } from "reakit";

// As usual...
function SomeTabs() {
  return (
    <Fragment>
      <TabList>
        <Tab stopId="orders">Orders</Tab>
        <Tab stopId="transactions">Transactions</Tab>
      </TabList>
      <TabPanel stopId="orders">
        <p>List of orders</p>
      </TabPanel>
      <TabPanel stopId="transactions">
        <p>List of transactions</p>
      </TabPanel>
    </Fragment>
  );
}

// Custom with hooks
function SomeOtherTabs() {
  const tab = useTabState({ selectedId: "orders" });
  return (
    <Fragment>
      <div {...tab}>
     {/* build it custom here with what you get from the hook */}
    </Fragment>
  );
}
```

**Comment by diegohaz** [comment]
Hey @lluia. That's a tradeoff. But that's how Reakit has always been since `v0.1.0`. The only difference now is that instead of [`<Tabs.Container>`](https://v0.reakit.io/components/tabs) you will use `useTabState`.

The alternative would be using React Context underneath to avoid the need of state hooks and passing props. This would require an additional component wrapping all the others (something like `<TabProvider>`). 

I'm not super fan of this approach as this makes things implicit and harder to compose. You can always go from explicit to implicit (that is, you can create an API like you suggested with the current Reakit API), but the other way around would be difficult.

**Comment by lluia** [comment]
Thanks for the explanation @diegohaz ! 💯
