### ISSUE TITLE
Add support for IE11.

### ISSUE THREAD

**Issue by leerob** [reakit/reakit#360]
### Motivation

![image](https://user-images.githubusercontent.com/9113740/57937741-2e5b4a00-788c-11e9-89d6-6d3974f1d14a.png)
https://www.w3counter.com/globalstats.php

**Comment by diegohaz** [comment]
Thank you @leerob 

If anyone with more experience on this (I stopped making sites for IE a long time ago) is willing to try and fix the bugs (or at least identify them), I can help pointing to files and lines in the source code.

**Comment by leerob** [comment]
It'd be awesome to use Reakit, but we have to support IE11 due to lots of our users requiring older browser support. Viewing the docs did not work on IE11, either.

- For supporting IE11, most `flexbox` things should work, minus [`justify-content`](https://caniuse.com/#search=justify-content).

**Comment by diegohaz** [comment]
Alright, if the problem is only style, the `reakit` package should work on IE11 as it doesn't include any (with a few exceptions that shouldn't count). It may be using JavaScript that is not supported though, not sure.

The styles on the website depend on the [`reakit-system-palette`](https://github.com/reakit/reakit/tree/master/packages/reakit-system-palette) and [`reakit-system-bootstrap`](https://github.com/reakit/reakit/tree/master/packages/reakit-system-bootstrap) packages. Despite being used by the Reakit website, they are really experimental right now and I don't recommend using them in production.

`reakit-system-palette` takes care of the default color palettes:
https://github.com/reakit/reakit/blob/master/packages/reakit-system-palette/src/palette.ts

`reakit-system-bootstrap` uses `reakit-system-palette` to style Reakit components (there may be issues with IE11 here):
https://github.com/reakit/reakit/tree/master/packages/reakit-system-bootstrap/src

The website merges the systems and override some values in this file:
https://github.com/reakit/reakit/blob/f5585d7ceb9a08b0a71d90f8fdd619d9aa8abc07/packages/website/src/components/Provider.tsx

Website specific styles are spread across [`components`](https://github.com/reakit/reakit/tree/master/packages/website/src/components), [`pages`](https://github.com/reakit/reakit/tree/master/packages/website/src/pages) and [`templates`](https://github.com/reakit/reakit/tree/master/packages/website/src/templates). The code is a huge mess right now (I'm sorry about that, I had to prioritize the main package), but it shouldn't be hard to update the styles.

**Comment by fleischie** [comment]
Hello.

For an anecdote on why I am here, check the following details:
<details>
We are using `reakit` v0 at a client's project for quite some time now, which is also required to work on IE11.

I ported the project from v0 to v1 on friday, ultimately removing most of the basis components in favor of default DOM elements (e.g. `div` instead of `Box`, etc.). This seems to have worked out alright. When I remembered to check IE11 for compatability it failed to render the app.
</details>

The main issue I encountered was that `reakit` v1 is using `Array.prototype.find`, which is not supported by IE11: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility

I am open to get into this issue and add a polyfill, try to circumvent `Array.prototype.find`, etc. and to create an appropriate PR. Whatever works best for this project. :smile: :+1:

**Comment by fleischie** [comment]
What I find curious, is that `babel.config.js` contains `browsers: "defaults"` as config for production builds... and the minified bundle seems to have clauses that guard these array prototype functions (as `Yt` and `Zt`), but still they are used directly in code that is at the very beginning of the bundle output.

**Comment by fleischie** [comment]
OK, I tried to explicitly set `"ie 11"` as the compilation target but it still uses `e.find` in the compiled bundle... the defaults targets also include ie11, so I really don't understand what is going on... 🤔

**Comment by vhfmag** [comment]
@fleischie I think you may be missing the `useBuiltIns` options for `@babel/preset-env`: https://babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins. That said, I'm not sure `reakit` should include polyfills in its bundle, as several packages including their own polyfill each, for several features, can their consumer's bundle explode. Two other solutions to be considered are:

- Make it clear to consumers that `reakit` uses some modern ES features and recommend that they use babel to polyfill it (in that case, only one polyfill would be included per feature, instead of one per feature per package; it also shouldn't be too tricky to setup a cache in webpack for build-time performance)
- Just stop using some features (meh)

There's been a blog post from a Babel maintainer arguing for this, I'll like to it if I can find it.

**Comment by fleischie** [comment]
@vhfmag ok granted, I could potentially polyfill `.find` and `.findIndex` myself on a project level. But this issue specifically asks for support of IE11, so I assumed it would be desired to do this on a library level.

(Also technically you wouldn't really need to polyfill `.find` and `.findIndex` in its entirety, because `popper.js` uses a pretty "simple" `find` and `findIndex` wrapper.)

**Comment by vhfmag** [comment]
@fleischie I also understand that the solution being discussed here was to bundle it with polyfills, I just wanted to provide a counterpoint.

Does popperjs provide its own implementation of `find` and `findIndex`? If so, that should be same as the second solution I proposed, isn't it?

**Comment by vhfmag** [comment]
Another possible solution is to mark `corejs` as an external dependency in the bundler, so that its import statements are included in the final bundle and the consumers bundler can deduplicate it efficiently, but that would mean `reakit` would only be usable with a bundler.

**Comment by fleischie** [comment]
Yo, I found another thing in `reakit@1.0.0-beta2` : `src/Dialog/__utils/usePortalRef.ts` has [the following line](https://github.com/reakit/reakit/blob/website%401.0.0-beta.2/packages/reakit/src/Dialog/__utils/usePortalRef.ts#L14):

```typescript
  ...
  portalRef.current = dialog.closest(Portal.__selector) as HTMLElement;
  ...
```

which is not compiled away in any way and which is additionally not available in IE: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest.

As long as nobody says anything I guess I will add these things here and polyfill them in the app level. This is really not the desirable solution to this issue, but it will do for now.

**Comment by tom-sherman** [comment]
For bundle size alone, I would hesitate in adding library level polyfills for IE11. 

As @vhfmag mentioned, I think a better solution would be to make it clear that IE11 is not supported, and suggest that user's include their own polyfills.

Ideally Reakit would provide a list of APIs that may need polyfilling in older browsers so user's can write code to conditionally load these.

**Comment by fleischie** [comment]
There are two main issues with that:
- If bundle-size is the main concern, why not directly write this lib in es5 w/o external dependencies,
- IE11 might be the only browser that I as a developer care about no matter how "old" it is.

Disregarding that I still would appreciate anything regarsing this topic: a Caveat section in the Readme, a library-included polyfill, a refactored usage of non-IE11 Array functions (with/without polyfills), anything.

I will post my solution for this problem on monday if I don't forget, for anybody having the same issue.

**Comment by diegohaz** [comment]
Just to let you guys know that I'm gonna give this issue more attention over the next couple of weeks. Hopefully, we'll have the core library working on IE 11 with automated tests by the end of October.

**Comment by andycarrell** [comment]
We're using Reakit pretty extensively (Menu, Popover, Tooltip & Dialog) and I was able to get these components functioning on IE pretty well by adding a few polyfills. Could a simple solution be to add a package (`packages/reakit-polyfills`) for the one required? That way it would be opt in if you need to support IE (and other browsers)

**Comment by diegohaz** [comment]
@andycarrell Yes, that's an option! Can you share the list of polyfills you had to add in order to make it work?

**Comment by andycarrell** [comment]
I can give a list of polyfills we're using - it'll be more than is needed for reakit (since we depend on other libraries too)

This is the list we use:
```js
import "core-js/features/array/find";
import "core-js/features/array/find-index";
import "core-js/features/array/fill";
import "core-js/features/array/includes";
import "core-js/features/object/entries";
import "core-js/features/object/values";
import "core-js/features/map";
import "core-js/features/number/is-nan";
import "core-js/features/set";
import "core-js/features/string/includes";
import "core-js/features/string/repeat";
import "core-js/features/string/starts-with";

import "react-app-polyfill/ie11"; // Promise, Object.assign, 'core-js/features/symbol', 'core-js/features/array/from'

// Also 
// https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
// https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Polyfill
```
Would highly recommend taking each one out and seeing what fails to check if it's necessary

**Comment by tom-sherman** [comment]
Here are the polyfills we're using in our app that uses Reakit, all the tests pass in IE.

```javascript
import './promise'
import './array-find'
import 'core-js/features/object/assign'
import 'core-js/features/array/includes'
import 'core-js/features/object/entries'
import 'core-js/features/url'
import 'whatwg-fetch'
import './childnode-remove'
```

**Comment by diegohaz** [comment]
Thank you @andycarrell and @tom-sherman for sharing your solutions. From what I tested, these are the required polyfills for `reakit@1.0.0-beta.7` to work on IE11:

```js
import "core-js/features/array/find";
import "core-js/features/array/find-index";
import "core-js/features/array/includes";
import "core-js/features/object/entries";
import "core-js/features/object/values";
import "core-js/features/object/get-own-property-descriptors";
import "core-js/features/string/includes";
import "react-app-polyfill/ie11";
// Also
// https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
// https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Polyfill
```

Except for the DOM methods `closest` and `remove`, `@babel/preset-env` automatically adds the needed polyfills in production, so I think we should leave this to the user (either by using `@babel/preset-env` or importing the polyfills manually).
