### ISSUE TITLE
Losing functionality when styling

### ISSUE THREAD

**Issue by stramel** [reakit/reakit#396]
### Current behavior

When I wrap the `Button` from `reakit` v1 with `styled` it is losing the `Tabbable` functionality. You can notice the `StyledButton` is missing HTML attributes and does not tab/focus properly like the base button does.

### Steps to reproduce the bug

https://codesandbox.io/embed/reakit-o4r25

### Expected behavior

I would expect the same functionality and attributes on the HTML elements generated for both the `reakit` and `styled-components` version.

### Notes

I followed the Theming suggestion from the Migration v0 to v1 post. https://github.com/reakit/reakit/issues/350

/cc @diegohaz

**Comment by diegohaz** [comment]
Hi @stramel.

That's because you're using the `as` prop from Styled Components, not from Reakit (SC doesn't pass it down to the Reakit Button). So, you're actually overriding `Button` with `div`.

Unfortunately, that's a limitation on SC side (related: https://github.com/styled-components/styled-components/issues/2183#issuecomment-435692522). You can use the render props method instead:
```jsx
<StyledButton>
  {props => <div {...props}>Button</div>}
</StyledButton>
```

**Comment by stramel** [comment]
Thank you for the quick reply.

**Comment by Und3Rdo9** [comment]
@stramel  You could also use the new `forwardedAs` prop added in `styled-components` v4.3. When applied to your codesandbox it seems to properly keep the Button attributes. 
See: 
https://custom-elements-everywhere.com/ https://www.styled-components.com/docs/api#forwardedas-prop
