### ISSUE TITLE
How do you set defaultChecked on Checkbox?

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#405]
## 💬 Questions and Help

As seen in the below sandbox, passing `defaultChecked` to a `Checkbox` component doesn't seem to do anything.

https://codesandbox.io/s/reakit-fk3qk

Is this possible with Reakit?

**Comment by tom-sherman** [comment]
My current solution is to fire a `useEffect` on first render to update state.

```javascript
function App() {
  const {state, setState} = useCheckboxState();

  React.useEffect(() => {
    setState(true)
  }, [setState])
  

  return (
    <React.Fragment>
      <Checkbox {...{state, setState}} defaultChecked={true} />
    </React.Fragment>
  );
}
```

This obviously isn't ideal and I'm sure there's a nicer solution, I just can't see it.

**Comment by diegohaz** [comment]
Hey @tom-sherman. All state hooks (`useSomethingState`) in Reakit accept objects as initial state. You can learn more about it here: https://reakit.io/docs/managing-state/

You can do this:
```jsx
const checkbox = useCheckboxState({ state: true });

console.log(checkbox.state); // true
```

Example here: https://reakit.io/docs/checkbox/#usecheckboxstate

**Comment by tom-sherman** [comment]
Thanks, I should read the docs!

**Comment by diegohaz** [comment]
No worries. Your question helps to find points that aren't intuitive enough. 👍

**Comment by tom-sherman** [comment]
@diegohaz I was trying to get your solution to work initially, however the piece I was missing was that I need to pass it in as `{state: true}` and not just `true`.

I was trying to use the hook exactly how `React.setState` works. Is there ever a scenario where you would want to pass in a `setState` option to the `useCheckboxState` hook? Otherwise it might be more intuitive to do `useCheckboxState(true)`?

**Comment by diegohaz** [comment]
[`state` is the only option you can pass to `useCheckboxState`](https://reakit.io/docs/checkbox/#usecheckboxstate-1). So, yes, it would make sense to pass the value directly as an argument.

But, for the sake of consistency, **all** state hooks in the library behave similarly so you'll need to learn less things when using other Reakit components. Since objects address all of our use cases, that's a standard in the library.

Besides that, it's easier to introduce new features by using objects. [`useHiddenState`](https://reakit.io/docs/hidden/#usehiddenstate), for example, also had only one option, and we're able to introduce a new `animated` option without breaking anything because it uses an object.

**Comment by diegohaz** [comment]
But, of course, you can always create your own version of it:
```jsx
import { useCheckboxState as useBaseCheckboxState } from "reakit";

function useCheckboxState(state) {
  return useBaseCheckboxState({ state });
}

useCheckboxState(true);
```

**Comment by tom-sherman** [comment]
Thanks for explaining your reasoning on this, it's really useful 👋
