### ISSUE TITLE
Menu add prop: trigger (hover|click)

### ISSUE THREAD

**Issue by rumsky** [reakit/reakit#424]
## 🚀 Feature request
add prop 'trigger' on Menu by hover or click

**Comment by rumsky** [comment]
There are so many warnings ,when use menu like this:
![image](https://user-images.githubusercontent.com/12367395/63919019-76376300-ca70-11e9-9f43-4a655a2f5d58.png)
![image](https://user-images.githubusercontent.com/12367395/63919044-83ece880-ca70-11e9-998a-b9ded938d5b7.png)

**Comment by diegohaz** [comment]
I'm not seeing the warnings on the sandbox. Could you please post your code here?

**Comment by rumsky** [comment]
When I add hover animation(like :https://codesandbox.io/s/reakit-animated-mm5u8?from-embed) warning error occur. 
My code repos: https://github.com/rumsky/next-with-reakit

**Comment by diegohaz** [comment]
Thanks for the code.

So, the problem is that you're using the `as` prop from `styled-components`, not from Reakit. [Styled components have their own `as` prop that might conflict with some libraries](https://github.com/styled-components/styled-components/issues/2183). The component you pass to SC's `as` will replace the one you passed to `styled()`.

```jsx
import styled from "styled-components";
import { Menu } from "reakit";
import { animated } from "react-spring";

const StyledMenu = styled(Menu)``;

<StyledMenu as={animated.div} /> // it becomes styled(animated.div) instead of styled(Menu)
```

Since you're replacing `Menu`, it doesn't consume those props and you get the warning saying that they are being passed to the underlying HTML element.

A solution is to use Reakit [render props](https://reakit.io/docs/basic-concepts/#render-props) instead:

```jsx
import styled from "styled-components";
import { Menu } from "reakit";
import { animated } from "react-spring";

const StyledMenu = styled(Menu)``;

<StyledMenu>{props => <animated.div {...props} />}</StyledMenu>
```

Related to #396

**Comment by rumsky** [comment]
Thanks! I solved it as your method.
