### ISSUE TITLE
Checkbox doesn't get checked if it is passed onChange prop

### ISSUE THREAD

**Issue by SpadarShut** [reakit/reakit#498]
### Current behavior

Checkbox doesn't get checked after click if it is passed `onChange` prop

### Steps to reproduce the bug

https://codesandbox.io/s/awesome-carson-2lcbi?fontsize=14

### Expected behavior

Clicking checkbox should check it (state is handled externally)

### Possible solutions

Looks like the checkbox gets unchecked during `useDelayedEvent` hook lifetime. This happens after the hook saves the event to state and before the effect with original `onChange` handler gets fired.

### Environment

```sh
 System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 82.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 67.0.4
    Safari: 13.0.2
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-dom: 16.12.0 => 16.12.0 
    react-final-form: 6.3.1 => 6.3.1 
    reakit: 1.0.0-beta.12 => 1.0.0-beta.12 

```

**Comment by tom-sherman** [comment]
You can get this working by passing some checkbox state into the Reakit Checkbox component: https://codesandbox.io/s/jolly-cerf-yng3s

You can read up on the "why" of the above here: https://reakit.io/docs/managing-state/

**Comment by diegohaz** [comment]
@SpadarShut Thanks for opening the issue! It's a little bit tricky to understand it as your CodeSandbox doesn't quite work (even with Material UI Checkbox). You need to spread `Field`'s `{...props.input}` into the checkboxes.

You can solve that my doing either what @tom-sherman proposed or by replacing the internal Reakit Checkbox `onChange` altogether:

```jsx
import { Checkbox } from "reakit";

function MyCheckbox(props) {
  return (
    <Checkbox {...props.input}>
      {({ onChange, ...checkboxProps }) => (
        <input {...checkboxProps} onChange={props.input.onChange} />
      )}
    </Checkbox>
  );
}

<Field name="reakit" type="checkbox" component={MyCheckbox} />
```

Note that you can do that (replace props) with all Reakit components. And that's often handful to work around some problems like this one.

That said, it should be working seamlessly. I'm marking this issue as a bug so we can investigate what's happening. Since this works fine as a controlled checkbox (that is, passing your on `checked` and `onChange` values), I guess that's something with `react-final-form` implementation.

**Comment by diegohaz** [comment]
This is the `react-final-form` `onChange` implementation: https://github.com/final-form/react-final-form/blob/213a397c9e9f2d3448f0c5457e5f2c9606f6e6cc/src/useField.js#L143-L175

We should be able to reproduce that without `react-final-form` within a test here: https://github.com/reakit/reakit/blob/master/packages/reakit/src/Checkbox/__tests__/index-test.tsx

**Comment by SpadarShut** [comment]
@diegohaz @tom-sherman Should this be working? I expect it to be, but this actually doesn't work.

https://codesandbox.io/s/fast-leftpad-d6nbd

```jsx
const App = function() {
  const [checked, setChecked] = React.useState(false);
  return (
      <Checkbox
        checked={checked}
        onChange={e => {
          setChecked(e.target.checked);
        }}
      />
  );
};

```

**Comment by diegohaz** [comment]
Yep! That should work. We should fix that!
