### ISSUE TITLE
Form method `reset()` not working, Add FormResetButton

### ISSUE THREAD

**Issue by Saeris** [reakit/reakit#502]
### Current behavior

Currently there isn't a button to use with `useFormState` to reset a form, similar to the existing submit, push and remove buttons. This means if you try to spread the form state on Reakit's `Button` element or a native HTML button element, you'll get numerous invalid prop errors, or you'll have to wire up individual props yourself.

If you manually call `form.reset()`, `form.values` does not get reset to `initialValues` as expected.

### Steps to reproduce the bug

Here's a Sandbox where the problem was observed:

https://codesandbox.io/s/codesadbox-prototyping-playground-lf0v3?fontsize=14&hidenavigation=1&initialpath=%2Fu&module=%2Fsrc%2Fpages%2FProfile%2FUserInfo%2FUserInfo.tsx&theme=dark

This should open the file containing the form as well as the page where the form is being used. Layout and logic are contained in `UserInfo.tsx`, styling of primitives are inside of `elements.ts`. Sorry for not providing a simpler example.

Let me know if you need any additional info!

**Comment by tom-sherman** [comment]
For consistency it does make sense to add a `FormResetButton` component but I'm not sure if it offers any benefits over just wiring it up yourself, as you have done.

`FormSubmitButton` has extra state logic so it requires it's own component & hook, I'm not sure that would be the case for a reset button.

**Comment by diegohaz** [comment]
@Saeris It seems to work as expected to me too! The `Other places` fields aren't working because you're looping through the initial values of `socialLinks`. Changing it to `form.values.socialLinks` works: https://codesandbox.io/s/codesadbox-prototyping-playground-9obwc

Pressing `Cancel` in the sandbox above will reset both the `bio` input and the `socialLinks`. Also, it's fine to use `i` as the `key` prop when using `form.values.someArray` as long as you don't have any sorting feature.

The reason you have to pass `value` and `onChange` to the bio input is because it's not a `FormInput`. It's getting replaced altogether by `TextareaAutosize` (`styled-components` replaces custom components when you use their `as` prop).

This should work:
```jsx
export const BioInput = styled(Input).attrs({
  forwardedAs: TextareaAutosize, // https://www.styled-components.com/docs/api#forwardedas-prop
  rows: 3,
  maxLength: 280,
  async: true
})`
  resize: none;
`;
```

**Comment by Saeris** [comment]
@diegohaz thanks for the tips! I've been staring at this component for the past two days so I had an inkling I was missing something obvious.

I thought `reset(0` was broken because the logged object wasn't returning the expected value for `socialLinks`, after hitting cancel it would log an empty string when I removed an item.

@tom-sherman true it might not be all that useful other than to reduce confusion, since the pattern used throughout the library is to spread properties of a state hook.

If anything, it wasn't clear from the documentation how to implement a form reset button, as even the `reset()` method isn't mentioned anywhere and it's usage has to be inferred from the source code.

**Comment by Saeris** [comment]
So actually @diegohaz I tried the sandbox you linked and the reset problem persists.

Try the following:

1. Click Edit Profile
2. Remove a link by clicking the X button
3. Click Cancel

The expected behavior is that the link which was removed should be back.

**Comment by diegohaz** [comment]
That was done that way so you can use `i` as `key`. Otherwise, indexes would change when you remove an item, and you would have to create an unique id for each item, which is not convenient. Using the value as the key (`url` in your case) also doesn't work since the whole component would be re-mounted on every change.

When you `form.remove()`, that array item gets `delete`d: https://github.com/reakit/reakit/blob/bd5390ccaa6209c4fa9193a8673f5b34adc67e7d/packages/reakit/src/Form/FormState.ts#L266-L273

In fact, that item is not `undefined`. It doesn't exist, or something like that. You can loop through that array ignoring that item and keeping indexes unchanged:

![image](https://user-images.githubusercontent.com/3068563/69436818-e0367000-0d20-11ea-908c-e7400c509906.png)

**But**, it may be the cause of `reset()` not reverting those values to the initial state. I'm going to investigate that.

**Comment by diegohaz** [comment]
It seems that #503 will fix this. Updated my CodeSandbox with the version published by CodeSandbox CI: https://codesandbox.io/s/codesadbox-prototyping-playground-9obwc?fontsize=14&hidenavigation=1&initialpath=%2Fu&module=%2Fsrc%2Fpages%2FProfile%2FUserInfo%2FUserInfo.tsx&theme=dark

By the way, CodeSandbox CI is amazing! Where can I suggest features? I'd like that the bot had included the querystring and, possibly, sandboxes in comments (like mine).

**Comment by Saeris** [comment]
@diegohaz awesome! Thanks for addressing this so quickly!

We always welcome feature requests via our issue board. I know we've discussed sandboxes in comments before, though I think the conclusion was supporting it would be a bit of a technical challenge and that's why it didn't make the initial release. I would assume it's still under consideration though. Ives would be the one to talk to about CI, it's one of his pet projects.

**Comment by diegohaz** [comment]
Cool!

Regarding the lack of documentation on `form.reset()`. The whole documentation doesn't include the props returned by state hooks, which is something we could improve.

This runs on `npm run docs`. Currently, it only shows the initial state options:
https://github.com/reakit/reakit/blob/bd5390ccaa6209c4fa9193a8673f5b34adc67e7d/scripts/build/utils.js#L585-L586

I guess that's a matter of adding an additional check there (something like `isStateReturnDeclaration`).

And `FormResetButton` is something we could do for sure.
