### ISSUE TITLE
Exit animation spying on wrong transitionEnd event

### ISSUE THREAD

**Issue by Grsmto** [reakit/reakit#531]
## 🐛 Bug report

Hi!

### Current behavior
The exit animation when using `unstable_animated` seems to be listening to the wrong element in the specific scenario of the following CodeSandbox.
Please notice that this only happen when the underlying `MenuItem` is using the `as` prop.

My assumption is that the `unstable_animated` is spying on the wrong `transitionEnd` event. But I'm not sure.

### Steps to reproduce the bug

1. Open sandbox:  https://codesandbox.io/s/reakit-enterleave-animation-3sysm
2. Click on "Menu"
3. Immediately click again on "Menu"
4. The exit transition happening is the wrong one

### Expected behavior

The exit transition should be the one assigned to the `Menu` element.

### Possible solutions

I couldn't figure out a solution for this. Just a workaround of removing the transition on child component.

**Comment by diegohaz** [comment]
Thanks for the reproduction! Maybe checking `event.currentTarget === event.target` inside the internal `onTransitionEnd` handler can solve this issue, but I'm not sure if this could impact other cases where you really want to listen to a transition in a child component.

Another workaround I found is adding `onTransitionEnd={event => event.stopPropagation()}` on your `MenuItem`s.

And I've got no idea why this only happens when using the `as` prop.
