### ISSUE TITLE
Ref on child of Portal has no height or width the first render

### ISSUE THREAD

**Issue by atomicpages** [reakit/reakit#532]
### Current behavior

Ref on child of `Portal` has no height or width the first render.

```js
function useComputedHeight() {
  const [size, setSize] = React.useState({
    width: undefined,
    height: undefined
  });

  const ref = React.createRef(null);

  React.useLayoutEffect(() => {
    if (ref.current) {
      setSize({
        width: ref.current.offsetWidth,
        height: ref.current.offsetHeight
      });
    }
  }, [ref.current]);

  return { ref, size };
}

const Greeting = ({ title }) => {
  const { ref, size } = useComputedHeight();

  return (
    <div className="App" ref={ref}>
      <h1>Hello {title}</h1>
      <h2>
        Size is {size.width}px by {size.height}px
      </h2>
    </div>
  );
};

export default function App() {
  return (
    <Portal>
      <Greeting title="Reakit Portal" />
    </Portal>
  );
}
```

This behavior is not reproducible using `ReactDOM.createPortal`.

### Steps to reproduce the bug

Visit and see output https://codesandbox.io/s/blissful-davinci-crxyu

### Expected behavior

Don't render the portal until the [context element has been appended to the body](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Portal/Portal.tsx#L36).

**Comment by diegohaz** [comment]
What if you use `React.useRef()` instead of `React.createRef()`?

**Comment by atomicpages** [comment]
Same behavior ☹️

**Comment by diegohaz** [comment]
There's a few things we can try here:

https://github.com/reakit/reakit/blob/301fbcadace6c2a472a054ec18198b52df35328d/packages/reakit/src/Portal/Portal.tsx#L34-L40

- Try to use `useLayoutEffect` ([`useIsomorphicEffect`](https://github.com/reakit/reakit/blob/47434b209138e976bb85085726f9867ee130f710/packages/website/src/hooks/useScrolled.ts#L7)) instead of `useEffect` so it appends the portal before the next browser repaint.
- As you mentioned, render the React Portal only after the host node has been appended into the DOM.

**Comment by atomicpages** [comment]
I'll give it a go @diegohaz. Thanks for the suggestions!

**Comment by diegohaz** [comment]
It's been *partially* fixed by #547

With those changes you can access the dimensions using `useEffect` or `useLayoutEffect` + `requestAnimationFrame`/`setTimeout`.

The behavior is different with React Portal only because you're putting it into an element that is already in the DOM (`document.body`). If you use the same method as in the [React Portal docs](https://reactjs.org/docs/portals.html), it'll be the same as with Reakit `Portal`.

**Comment by namjul** [comment]
I came across this issue by using the `autoFocus` attribute and it would not work with reakit's `Portal` but with `react-portal`.

There seems to be two approaches where in the one taken by [`react-portal`](https://github.com/tajo/react-portal/blob/master/src/Portal.js#L20) you add the container first and then use `createPortal` to render the tree into it. The other, and taken by reakit, you first render the react tree and than add the container to the DOM.

The problem with that approach is that for example the `autoFocus` attribues won't work because the react tree gets rendered before it actually lands in the DOM. So react internal internal [`autoFocus` behavior](https://github.com/facebook/react/issues/11851#issuecomment-351672131) has no effect.

My intention here is just to point this out and notify that we need to use `react-portal` for that case.

**Comment by diegohaz** [comment]
Thanks for the info @namjul!

I think the difference is that `react-portal` creates and appends the container element into the DOM synchronously in the render phase, whereas we do this in a `useLayoutEffect` callback.

Their approach is really interesting, and we can look into doing something similar here. But I'm not sure how safe is it, given that's not [what the React docs recommend](https://reactjs.org/docs/portals.html#event-bubbling-through-portals).

If you provide a CodeSandbox example of what you're trying to do, I can see if there's an alternative way or workaround to it.

**Comment by namjul** [comment]
Ah, did not catch that comment in the docs. Yea they are kind of implicitly recommending that approach. Wondering why that is necessary because at a first glance it does not seem to effect the bubbling. And they even reference the `autoFocus` attribute..

I created an example based on the react docs example https://codesandbox.io/s/dry-sky-tizqz and solved it with state like they suggest. 

For this to work with reakit's `Portal` a similar prop like the `onAppend` would be needed?

**Comment by diegohaz** [comment]
I don't think a custom prop is needed in this case as you could solve it with a simple `useLayoutEffect`: https://codesandbox.io/s/reakit-portal-with-autofocus-fdjw5

```jsx
const [show, setShow] = React.useState(false);

React.useLayoutEffect(() => setShow(true), []);

return <Portal>{show && <button autoFocus>Button</button>}</Portal>;
```

**Comment by diegohaz** [comment]
> Wondering why that is necessary because at a first glance it does not seem to effect the bubbling

My first guess is that it may not be safe for concurrent mode.

**Comment by namjul** [comment]
thank you @diegohaz. My sense for now is that your proposed way with using `useLayoutHook` is the way to handle that and it works perfectly fine in our case.

**Comment by okonet** [comment]
> what the React docs recommend.

I'm wondering what part of this page you're referring exactly since I can't find any recommendations regrind this there.

**Comment by diegohaz** [comment]
> I'm wondering what part of this page you're referring exactly since I can't find any recommendations regrind this there.

The example on the docs show the container DOM element being appended to the modal root element in `componentDidMount`, which is equivalent to `useLayoutEffect`.

**Comment by okonet** [comment]
Yeah, thanks! I found the comment on the GitHub page which isn't visible on their website (bug?).
