### ISSUE TITLE
Accessiblity issue: Portal Popover breaks keyboard navigation

### ISSUE THREAD

**Issue by c10b10** [reakit/reakit#566]
### Current behavior

When you open the portal version of the Popover, and then try to navigate out of it using Tab, that will take you to the beginning of the page instead of to the next element in the document.

### Steps to reproduce the bug

For some reason, I can't reproduce it in CodeSandbox, but it can be reproduced by:

1. Going to https://reakit.io/docs/popover/
2. Modifying the first example (the one in the Usage section) to add the `unstable_portal` prop on the `Popover` component
3. Clicking on the "Open Popover" button or use `Tab` to navigate to it and open it with `Space`
4. Pressing `Tab`

### Expected behavior

It should navigate to the next element, which in this case is the `CodeMirror` element. Unfortunately it does not. It goes back to the start of the page. 

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 242.62 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Brave Browser: 80.1.3.115
    Chrome: 80.0.3987.106
    Firefox: 66.0.1
    Safari: 13.0.5
```

**Comment by diegohaz** [comment]
This is a known issue, but not specific to Reakit, this is just how React Portals work. Since you attach elements into other parts of the DOM (in this case, at the end of the document), they follow the normal tab sequence.

Because of this inconsistency, the `unstable_portal` prop has been removed from `Popover` in the version `1.0.0-beta.15`. So I guess this doesn't apply anymore (I can't even reproduce your use case in the docs). But you can achieve the same result by wrapping `Popover` within a `Portal`:

```jsx
import { Portal, Popover } from "reakit";
<Portal>
  <Popover />
</Portal>
```

Due to how React Portals work, you'll get the same issue you're describing. I just tweeted a workaround on Twitter: https://twitter.com/diegohaz/status/1229837604977348612

You can see this in practice on this CodeSandbox: https://codesandbox.io/s/reakit-portal-popover-tab-sequence-d4vb3

**Comment by c10b10** [comment]
> Because of this inconsistency, the unstable_portal prop has been removed from Popover in the version 1.0.0-beta.15. So I guess this doesn't apply anymore (I can't even reproduce your use case in the docs). But you can achieve the same result by wrapping Popover within a Portal:

I guess this explains why I wasn't able to reproduce the issue in CodeSandbox.

I'm going to give Focus Traps a try. Thanks @diegohaz!
