### ISSUE TITLE
Allow consumer to set (more) popper modifiers

### ISSUE THREAD

**Issue by MortenHofft** [reakit/reakit#606]
### Motivation

I miss being more in control of my popover. Popper provides a lot of customisation options that would be useful to expose in the popover component. 
https://github.com/reakit/reakit/blob/master/packages/reakit/src/Popover/PopoverState.ts

### Example

I could for example set my popover to not overflow the body using [altAxis: true](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#altaxis)

### Possible implementations

Expose additional modifiers in https://github.com/reakit/reakit/blob/master/packages/reakit/src/Popover/PopoverState.ts#L152 just like flip, preventOverflow etc

**Comment by gziolo** [comment]
Is there any reason why all existing options from Popper aren’t exposed? 

Aside, there is TS support added to Popper so it might be much easier to have it all integrated by re-exporting their types for placement and other options.

**Comment by diegohaz** [comment]
The problem with re-exporting anything from a third party dependency is that any major version update in the dependency will potentially require a major version update here, which is not ideal.

That could've happened when we upgraded to Popper.js v2. But, since we have full control over the things we expose, that was easier to update and we could keep the Popover/Menu/Tooltip APIs intact.

There's also the possibility that we get rid of the dependency in the future, even though it's unlikely to happen to Popper.js anytime soon, as I don't see any better alternative arising. But, If this happens, though, we would have to implement every feature we committed to provide.

That said, I'm not against exposing any Popper.js feature. If something is common enough, that should definitely be exposed. For features that aren't a common need, maybe it's better to let the user create their own `usePopoverState` with a Popper.js instance they control. After all, Reakit provides this kind of flexibility for a reason. 😄

**Comment by gziolo** [comment]
> That said, I'm not against exposing any Popper.js feature. If something is common enough, that should definitely be exposed. For features that aren't a common need, maybe it's better to let the user create their own `usePopoverState` with a Popper.js instance they control. After all, Reakit provides this kind of flexibility for a reason. 😄

I agree with all that. I would probably approach it the same if I were to decide about API for the project I work for 🤣 It's funny how different your thinking is when you comment as the library's consumer. It's a good reminder to think like a maintainer when asking for feature changes.

**Comment by FezVrasta** [comment]
I suppose Reakit could make an exception and warn users that the `popperOptions` property is an escape hatch that is not guaranteed to follow semver.

**Comment by MortenHofft** [comment]
This shows my issue and motivation:
https://codesandbox.io/s/reakit-popover-overflow-8mleu?file=/index.js

The popover overflows in body bottom. And setting preventOverflow doesn't help as it only deals with horisontal overflow (vertical is a setting that defaults to false).

I'm simply not sure how to handle this within Reakit. Am I missing something? I could set placement to `auto` of course, but then I would loose my prefered default which is `bottom`.

**Comment by diegohaz** [comment]
@MortenHofft What's the option on Popper.js that would solve that?

**Comment by folz** [comment]
I was about to open an issue about this as well. I'd also appreciate an API for customizing or creating arbitrary popper.js modifiers for Popover and related components.

My specific use case - we have new Tooltip designs that call for rounded borders. The TooltipArrow is placed such that it starts to diverge from the Tooltip:

<img width="221" alt="Screen Shot 2020-06-22 at 4 06 18 PM" src="https://user-images.githubusercontent.com/299281/85343675-50b59300-b4a2-11ea-8287-f7a6b0a94bba.png">

The `arrow` modifier in theory supports placing the TooltipArrow closer in to the Tooltip center ([docs](https://popper.js.org/docs/v2/modifiers/arrow/#padding)), but Reakit doesn't provide a way to set the `arrow` modifier as used in reakit ([source](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Popover/PopoverState.ts#L194)).

I was originally going to file an issue requesting that Reakit support arrow padding directly, but there are a few issues already about various popper modifiers: #196, #507, #517, and my own #527. This makes me think there should be a way to generally configure modifiers, instead of exposing a prop for each possible modifier.

**Comment by diegohaz** [comment]
Thanks for the feedback @folz! It's very important!

Have you tried to replace the `PopoverArrow` children with another SVG or even use another element as the arrow that would adapt better to your tooltip design? Looks like it could work.

**Comment by folz** [comment]
So the TooltipArrow's SVG works for me when I forked reakit locally and edited the `arrow` modifier to move it a little closer to the center, and the `offset` to counterbalance:

<img width="216" alt="Screen Shot 2020-06-22 at 5 06 15 PM" src="https://user-images.githubusercontent.com/299281/85346561-b017a100-b4aa-11ea-8516-5ba7d1291d4f.png">

I've tried using other SVGs from our icon library and I've tried rescaling the SVG to overlap with the Tooltip. I don't think my particular issue is the size/shape of the SVG. Instead the arrow modifier needs to be positioned slightly differently than the reakit default, because the border radius means there's less visual space to place the arrow.

This is why I think it's correct to make that change to the `arrow` modifier instead of changing the Arrow element's SVG. For this use case, I'd be happy with an `unstable_arrow` option to match `unstable_offset`, etc. But then I worry I'll be back in a month with another modifier option PR.

**Comment by diegohaz** [comment]
Adding individual options for common needs is the best solution I can think of right now. Popper.js is an implementation detail, and exposing something such as `popperOptions`, even if it's marked as experimental, will create more frustration in the future.

The ideal solution is to make it easier for people to extend or replace `usePopoverState`/`useTooltipState` with their own state hook, so they have full control over it, which may include creating their own Popper object.

**Comment by MortenHofft** [comment]
> @MortenHofft What's the option on Popper.js that would solve that?

[altAxis: true](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#altaxis) in my case.

I like the ideal solution 😄  of making it easy to extend `usePopoverState`, but currently I wouldn't know how to without writing my component from scratch. That might well be my lack og imagination though.

**Comment by FezVrasta** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by tom-sherman** [comment]
This seems like a good feature to have at some point, even if we're not sure of the details yet. I've marked it as not-stale for this reason so that the bot doesn't bother us any more 😂

**Comment by brianespinosa** [comment]
Another use case I have is the need to have the Popover match the width of the reference. There is a `sameWidth` community modifier that does this: https://codesandbox.io/s/bitter-sky-pe3z9?file=/src/index.js

I also need to limit the height to the viewport, including on mobile devices where `vh` does not necessarily work with a long page. The `maxSize` modifier would allow for this.

**Comment by brianespinosa** [comment]
@diegohaz would you be open to a PR that exposes Popper modifiers on `<Popover />` with an `unstable_` prefix to the prop? Maybe `unstable_modifiers` or `unstable_popperModifiers`? This way, if anyone does use it, we know we are doing so at our own risk and we are responsible for being aware of what we are doing. I'd really like to not have to maintain a separate Popover fork and keep it up to date with what we have here in Reakit if possible... however, if you feel this should not come in, I understand.

**Comment by diegohaz** [comment]
@brianespinosa Yeah! We can have that until we find a better solution.

**Comment by diegohaz** [comment]
`unstable_popperModifiers` has been released in `reakit@next`.

**Comment by brianespinosa** [comment]
@diegohaz do you have an idea on when you plan on shipping `1.4.0`? I know you pushed the alpha a couple months ago with `unstable_popperModifiers`. Just curious if there's a timeline or if you have other things you want to include in the minor version.
