### ISSUE TITLE
Tab component not passing through `disabled` prop 

### ISSUE THREAD

**Issue by TheSisb** [reakit/reakit#659]
## 🐛 Bug report

Passing a `disabled` prop through the Tab component down to the (i.e.: `as={Button}`) component doesn't work.

### Current behavior

I'm using the Tab component like so:
```
<Tab as={Button} disabled>Disabled Tab</Tab>
```
and the disabled prop is being stripped before being passed down to my Button component, so it isn't styling it correctly.

### Steps to reproduce the bug

https://codesandbox.io/s/ecstatic-cloud-sbwv4?file=/index.js

### Expected behavior

Underlying component should receive the `disabled` prop, to style correctly.

### Possible solutions

N/A

### Environment

N/A

**Comment by diegohaz** [comment]
Hey @TheSisb!

The `Tab` component has the `focusable` prop set to `true` by default, which means that even when you mark it as `disabled`, it'll not pass the `disabled` prop to the underlying element. Instead, it passes `aria-disabled`. This is so the tab element remains focusable even though it's disabled.

So, you have some options:
 - In the `Button` component, check the `aria-disabled` prop instead of `disabled`.
 - Set `focusable` to `false` on the `Tab` component.
 - Use [render props](https://reakit.io/docs/basic-concepts/#render-props) instead of the `as` prop and pass the `disabled` prop directly to the `Button` component.

**Comment by TheSisb** [comment]
Thank you!

**Comment by Slapbox** [comment]
@diegohaz shouldn't `focusable={false}` on a `<Tab />` imply that the tab will not focus itself when programmatically activated with `tab.next()` and `tab.previous()`?

We're upgrading from `beta.14` and previously we were able to prevent the tab from becoming focused, but now nothing seems capable of preventing the tab from focusing itself. 

Even trying to select the tab's contents instead like this fails. The `changedTabs` state is just for example's sake.

`this.setState({ changedTabs: true }, () => window.requestAnimationFrame(inputRef.current.focus)`

**Comment by diegohaz** [comment]
> @diegohaz shouldn't `focusable={false}` on a `<Tab />` imply that the tab will not focus itself when programmatically activated with `tab.next()` and `tab.previous()`?

It seems to work fine here. Could you provide a CodeSandbox?

> **Edit:** Followup question, is there a way to disable all arrows on the Tab components? We're using Reakit outside of a browser environment and we use `Ctrl+Tab` and `Ctrl+Shift+Tab` instead.

I think you can do something like this:
```jsx
<Tab {...tab}>
  {htmlProps => (<button {...htmlProps} onKeyDown={myOwnLogic} />)}
</Tab>
```

**Comment by Slapbox** [comment]
@diegohaz first, your speedy replies around the clock marvel me! Thanks for the reply!

Here's a repro for the issue with preventing the Tab component from taking focus. https://codesandbox.io/s/gallant-shaw-6uuwc?file=/index.js - you can use <kbd>z</kbd> for previous tab and <kbd>.</kbd> for next tab. I didn't include any of our additional logic for trying to recapture focus, since I think the tab shouldn't have the focus to begin with.

Regarding disabling the arrow keys, your snippet works great! I really appreciate it!

**Comment by diegohaz** [comment]
Got it now! That's not what `focusable` does. The fact that it's working as you described on `beta.14` is unintentional.

When `focusable` is `true`, it enables `disabled` items to receive focus. If the item is not `disabled`, it has no effect.

State functions that don't start with `set` usually have side effects. `tab.next` and `tab.previous` will call `tab.setSelectedId` underneath and move focus. If you want to select a tab without moving focus you have to use `tab.setSelectedId` directly.

https://codesandbox.io/s/lucid-blackwell-2ufv9?file=/index.js

(Replaced `GlobalHotKeys` by a custom implementation, because that package has a lot of bugs).

**Comment by Slapbox** [comment]
@diegohaz that works great! Makes sense about the side effects. That's really useful to know about functions that start with `set`. Thanks a lot for your help!

**Comment by Slapbox** [comment]
Hey @diegohaz I just noticed that actually the `state.items` array is consistently empty. As a result the example code actually only toggles between two tabs and can't work with a third. Also, it seems that that method would not be able to support looping through tabs, right?

**Comment by diegohaz** [comment]
`state.items` is not empty. The issue was that `tab.setCurrentId` should've been called as well: https://codesandbox.io/s/sad-curie-hjvlw

> Also, it seems that that method would not be able to support looping through tabs, right?

You would have to implement your own logic for that.

**Comment by diegohaz** [comment]
Depending on what you're doing, it's probably better to just recapture focus.

**Comment by Slapbox** [comment]
Whoops, I see now that the `state.items` being empty was due to how I was invoking the methods. Unfortunately, after correcting this, it's again become apparent that changing tabs is preventing me from managing the focus with my own logic.

----

The trouble with simply recapturing focus hasn't been something I can get to work consistently since upgrading. That's what I was previously doing in `beta.14`, but the behavior is spotty at best now. This is the case even when I try to focus an element that exists outside of the `TabPanel`s, to remove that variable.

Is there some better way to recapture focus that you might recommend? The only thing I can think of that I haven't tried is using arbitrarily timed `setTimeout`s. It would be great if `tab.next()` took a callback, although maybe there are reasons this wouldn't make sense.

What had worked in `beta.14` was something like:

```js
const handlers = {
  nextTab: () => {
    tab.next();
    onNextTab();
  },
  prevTab: () => {
    tab.previous();
    onPrevTab();
  },
}

// and then onNextTab/onPrevTab were callbacks from parents which would call something like
function onNextTab() {
   //  rAQ inside setState callback, called after Reakit methods
  this.setState({ changedTabs: true }, () => window.requestAnimationFrame(inputRef.current.focus));
}

```

**Comment by tom-sherman** [comment]
If you want to select a new tab but move the focus elsewhere you can use `setCurrentId` (which will just change the active tab) and then handle the focus yourself - right now it looks like you're fighting against Reakit's internal handling of focus due to the use of next/previous.

**Comment by Slapbox** [comment]
@tom-sherman calling `tab.setCurrentId` doesn't actually cause the tab to change in any way as far as I can tell. Calling just `tab.setSelectedId` similarly does not open the desired tab programmatically.

If we call both, then we get closer, but the selected tab's `aria-selected` property will be `false` so the visual appearance will not be correct.

Is there some flaw in my approach? https://codesandbox.io/s/ancient-microservice-jv667?file=/index.js
