### ISSUE TITLE
Radio state with Safari and Firefox

### ISSUE THREAD

**Issue by frassinier** [reakit/reakit#681]
## 🐛 Bug report

Radio state with Safari and Firefox is not really updated

### Current behavior

I try to lean on the Radio state using `<RadioGroup>` and `<Radio/>`
If I use Chrome or Edge, its `currentId` will change, not with Safari or Firefox :(

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.
https://codesandbox.io/s/fancy-fog-wf1sx

Let's see in the console what happens when you select another radio

### Expected behavior

Obviously, I need to get this value staying up to date

### Possible solutions

I don't know 

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 154.10 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Chrome Canary: 85.0.4177.0
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-i18next: ^11.5.0 => 11.5.0 
    react-inlinesvg: ^1.2.0 => 1.2.0 
    react-is: ^16.13.1 => 16.13.1 
    reakit: ^1.0.4 => 1.0.4 
```

**Comment by diegohaz** [comment]
Thanks for reporting it @frassinier!

I believe it has to do with the fact that Firefox (on MacOS) and Safari don't move focus to native radio elements when you click on them. And since `currentId` tracks only focus, it's not updated. You could even add an `onFocus` handler to the radio element, and it wouldn't be executed at all. `radio.state` is correctly updated though.

We do have a mechanism to make this behavior consistent across browsers/platforms on `Tabbable` components (and `Radio` uses it): https://github.com/reakit/reakit/blob/11684363f698a57d3c974b8b7cd197bbc27d449d/packages/reakit/src/Tabbable/Tabbable.ts#L48-L107

But only native buttons (`<button>` or `<input type="button">`) are currently supported:
https://github.com/reakit/reakit/blob/11684363f698a57d3c974b8b7cd197bbc27d449d/packages/reakit/src/Tabbable/Tabbable.ts#L68

We could include radio buttons there too.

Out of curiosity, what's your use case to use `radio.currentId` on mouse clicks?

**Comment by frassinier** [comment]
Thank you @diegohaz!

I want to create a switch with a sliding indicator
![Jun-19-2020 17-34-55](https://user-images.githubusercontent.com/18534166/85150844-579a9680-b253-11ea-9d1e-b91d28556af7.gif)

So I have set up a hook to adapt its width and its position regarding the current selection.

**Comment by diegohaz** [comment]
Got it! Thanks!

I know that @itsjonq has worked on a very similar component in the past. And it seems to work great on Safari: https://react-viewport-frame.netlify.app/?path=/story/segmentcontrol--default

You can see the code [here](https://github.com/ItsJonQ/react-viewport-frame/blob/8a35e974d5e1847ced20552f39246a1fe66cf4b2/src/components/SegmentControl/SegmentControl.js). I guess it's not relying on `currentId`.

**Comment by frassinier** [comment]
Ok, kudos for @ItsJonQ's workaround.

The trick is to use `unstable_virtual` option with the radioState in addition to using data attribute on the main element representing the Radio.

Now, it works with webkit on my side too but keyboard gestures are still broken with Firefox. 

Can I suggest a PR for fixing this:
>But only native buttons (<button> or <input type="button">) are currently supported [...] We could include radio buttons there too.

**Comment by diegohaz** [comment]
Sure!

**Comment by diegohaz** [comment]
I'm anticipating that #683 will get quite complex. I wonder if just turning `Radio`s into buttons wouldn't be enough for your use case:
```jsx
<RadioGroup {...radio} aria-label="fruits">
  <Radio {...radio} value="apple" as="button">Apple</Radio>
  <Radio {...radio} value="orange" as="button">Orange</Radio>
  <Radio {...radio} value="watermelon" as="button">Watermelon</Radio>
</RadioGroup>
```

**Comment by frassinier** [comment]
It works like a charm using buttons, but I will still try to fix that as expected.
