### ISSUE TITLE
Automatically invert tooltip's position if there is not enough space

### ISSUE THREAD

**Issue by DoneDeal0** [reakit/reakit#705]
## 🚀 Feature request
Automatically invert tooltip's position if there is not enough space to display its content. The popover already does it. 

### Motivation
Never let the browser's edges hide the tooltip. 

### Example
const reakitTooltip = useTooltipState({placement: top});
=> placement automatically switches to bottom if there is not enough space.

**Comment by diegohaz** [comment]
Hi @DoneDeal0! It already does that, doesn't it?

If it's not working for you, could you please provide a CodeSandbox reproduction?

**Comment by DoneDeal0** [comment]
Hello @diegohaz , thanks for your answer! Right now, the automatic position only works for small content. For large texts (for example a list of countries chosen in a filter), the behaviour is broken. I have reproduced the issue in this sandbox:
https://codesandbox.io/s/react-hooks-usestate-forked-45t06?file=/src/index.js

I you remove some lorem ipsum, it will work again as expected. I suspect there is a length issue.

**Comment by tom-sherman** [comment]
In your example, it's showing at the top when there is not enough space to show the content at the bottom. Open the preview fullscreen and zoom out a bit if you have to, the tooltip will appear at the bottom if there is enough room, otherwise it'll default to show at the position you told it to show at.

I'm not sure how best to solve your problem, but I'd suggest that a tooltip isn't the right component when your content may be larger than the viewport.

**Comment by DoneDeal0** [comment]
Ok, my bad, it makes sense. I close the issue then. Thanks for your time!

**Comment by diegohaz** [comment]
Yeah, you'll be probably better using a Popover with a scrollable area inside. There are some discussions around hover popovers on #633. Any feedback there is highly appreciated!
