### ISSUE TITLE
Menu performance (delay when initially rendering many Menu's)

### ISSUE THREAD

**Issue by jxom** [reakit/reakit#730]
### Current behavior

For a component which consists of many `Menu` components (in the below example, there are 20 menus w/ 10 items in each). There seems to be a bit of a delay when initially rendering the menus.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/billowing-mountain-izt5v?file=/index.js

2. When you click on "Show menus", you will see a delay before the `Menu`s render

![menus](https://user-images.githubusercontent.com/7336481/91692989-b2cefa80-ebad-11ea-8980-2f11aa3f9307.gif)

3. Upon opening devtools, you will see the frame rate drops to 0 for about a second as the `Menu`'s are rendering

<img width="1649" alt="Screenshot 2020-08-31 at 5 09 26 pm" src="https://user-images.githubusercontent.com/7336481/91692807-5bc92580-ebad-11ea-8fa1-b0aa77c5d833.png">

### Expected behavior

Hopefully a delay which is unnoticeable by the user when "Show menus" is clicked.

### Possible solutions

I'm not exactly sure what the culprit is here to be honest, but upon investigation of the performance timeline in devtools, it looks like the `createComponent`, `createHook`, and popperjs fns (the `index.js`'s) are taking up a bit of time... Maybe something weird is happening in Popper?

<img width="823" alt="Screenshot 2020-08-31 at 5 11 21 pm" src="https://user-images.githubusercontent.com/7336481/91692810-5d92e900-ebad-11ea-8fc9-6333b8e085bf.png">

**Comment by diegohaz** [comment]
Thanks for investigating it @jxom! ❤️ 

It's mostly due to `reakit-system-bootstrap` and its use of CSS-in-JS. This is a known issue, but since `reakit-system-*` packages aren't production ready, it's not really a priority right now. Actually, since there hasn't been any meaningful progress on the `reakit-system-*` packages so far,  I'm thinking about giving up on that experiment altogether and providing CSS examples in the docs instead.

I forked your CodeSandbox and made this comparison between different approaches to render the Menu component. Without CSS-in-JS, the total render time drops to less than a half: https://codesandbox.io/s/reakit-menu-performance-h2wwn

The best approach is to conditionally render menu contents. This is something we can explore in the library in v2, but you could do this right now.

Concurrent mode feels faster although the total render time may be higher because it doesn't block interactions.

![Screenshot of comparison between multiple rendering approaches. See CodeSandbox link above for details](https://user-images.githubusercontent.com/3068563/91725344-f9543300-eb74-11ea-988d-b142a02db619.png)
