### ISSUE TITLE
Tooltip initial position in concurrent mode

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#852]
### Current behavior

The tooltip flashes at the top left corner in the first render when using concurrent mode.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/dazzling-feistel-tcroh?file=/index.js
2. Enable CPU throttling (6x) on the developer tools.
3. Refresh the app frame and move the mouse over the button.

### Expected behavior

The tooltip should not flash in a different position.

**Comment by FabianaFerreira** [comment]
Hi, @diegohaz. How are you? 
So, we noticed this bug while developing in the Faststore project and we need this to continue with the current implementation. Do you have any idea of when the PR will be merged? Thank you a lot! cc @emersonlaurentino

**Comment by diegohaz** [comment]
Hi @FabianaFerreira! Could you please use the version created for that PR and see if it fixes your problem? I'll merge that and release a new version then.

```
"reakit": "https://pkg.csb.dev/reakit/reakit/commit/1df45c42/reakit",
```

**Comment by polc** [comment]
Hi it fixed the issue for me, thanks !

**Comment by FabianaFerreira** [comment]
Hi, @diegohaz! How are you? 
I've already updated our project to use the current version that was merged a few days ago, thank you so much for helping us fix the problem! However, we're facing another weird behavior. In our case, for small screens, the first hover is appearing kind of padding to the right and it goes beyond the screen itself. If it's a bigger screen, it seems that the position also changes from the first hover to the following ones, but it's not that noticeable, because it does not cut a part of the information. [Here](https://recordit.co/hfj2mtiRSg) there is a gif showing the behavior and you can find below some screenshots:

First hover:
![image](https://user-images.githubusercontent.com/19495917/113728753-bccd5480-96cc-11eb-9df9-ba3686209026.png)
Second hover:
![image](https://user-images.githubusercontent.com/19495917/113728811-c9ea4380-96cc-11eb-9392-7560219f2578.png)

cc @emersonlaurentino

**Comment by diegohaz** [comment]
Hello @FabianaFerreira! Could you please create a new issue? A CodeSandbox would be awesome too.
