### ISSUE TITLE
Register MenuGroup

### ISSUE THREAD

**Issue by elitenoire** [reakit/reakit#888]
### Current behavior

MenuGroup does not get registered.

### Steps to reproduce the bug
Log the return value of  ```useMenuState``` hook from the Menu docs for a quick view.

![image](https://user-images.githubusercontent.com/25673419/127166574-d1da5a15-7a55-492d-a7d0-8e16374b1f9e.png)

**Comment by diegohaz** [comment]
Thanks for opening the issue @elitenoire.

The `MenuGroup` component is not supposed to be registered in the state. Actually, the `groups` and `groupId` states are meant to group items by rows in a [two-dimensional composite widget](https://reakit.io/docs/composite/#two-dimensional-navigation). They have no use in the Menu component since it's always one-dimensional. We'll likely change that in v2 to avoid this kind of confusion.

I'm closing this for now. If you need this information as a feature to do something else, please create a feature request issue with more details on the use case so we can discuss that further.
